[pytest]
addopts = -v --headed --browser=chromium --html=reports/html/report.html --self-contained-html --slowmo=200
testpaths = tests 
pythonpath = .

markers = 
    smoke: smoke tests
    regression: regression tests
    api: api tests
    ui: ui tests